"""Add models

Revision ID: c7157ab7e298
Revises: e6868d9c6af2
Create Date: 2022-03-31 19:49:14.388881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7157ab7e298'
down_revision = 'e6868d9c6af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_city', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_city')
    )
    op.add_column('place', sa.Column('city_id', sa.Integer(), nullable=False))
    op.add_column('place', sa.Column('rate', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'place', 'city', ['city_id'], ['id'])
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_constraint(None, 'place', type_='foreignkey')
    op.drop_column('place', 'rate')
    op.drop_column('place', 'city_id')
    op.drop_table('city')
    # ### end Alembic commands ###
