version: '3'

services:
  pg2:
    image: postgres # use latest official postgres version
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_flask
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  app_prod:
    build:
      context: .
      dockerfile: docker-build/Dockerfile
    environment:
      CONFIG_NAME: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://user:password@pg2/test_flask
    ports:
      - '5000:80'
    depends_on:
      - pg2

  app_dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_NAME: DevelopmentConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://user:password@pg2/test_flask
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    depends_on:
      - pg2

volumes:
  pg-data: